
server:
  port: 8080

spring:
  datasource:
    username: kanzhun
    password: kanzhun!@#kanzhun
    url: jdbc:mysql://192.168.1.38:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.liuyan.zbauto.mapper.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug