
server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.liuyan.zbauto.mapper.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug


wechat:
  appId: wxd86b7a6aab56f0ff
  secretId: ae7ed5e276ed27eae3d5bf9e17a6f5d1
  accessUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET